NEWS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("newspaper.urls")),
    path("blog/", include("blog_app.urls")),
    path("api/v1/", include("api.urls")),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

blog_app/urls.py
from django.urls import path

from blog_app import views

app_name='blog'

urlpatterns = [
    path("", views.PostListView.as_view(), name="post-list"),
    path("post-detail/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("draft-list/", views.DraftListView.as_view(), name="draft-list"),
    path("draft-detail/<int:pk>/", views.DraftDetailView.as_view(), name="draft-detail"),
    path("draft-publish/<int:pk>/", views.DraftPublishView.as_view(), name="draft-publish"),
    path("post-delete/<int:pk>/", views.PostDeleteView.as_view(), name="post-delete"),
    path("post-create/", views.PostCreateView.as_view(), name="post-create"),
    path("post-update/<int:pk>/", views.PostUpdateView.as_view(), name="post-update"),
    path("users/", views.UserReportView.as_view(), name="users",),
    
]

templates/aznews/about.html
{% extends "aznews/base.html" %}
{% load static %}

{% block content %}
<main>
    <!-- About US Start -->
    <div class="about-area">
        <div class="container">
            {% include "aznews/main/home/trending/trending_title.html" %}
            
            <div class="row">
                <div class="col-lg-8">
                    <!-- Trending Tittle -->
                    <div class="about-right mb-90">
                        <div class="about-img">
                            <img src="{% static 'aznews/assets/img/post/about_heor.jpg' %}" alt="">
                        </div>
                        <div class="section-tittle mb-30 pt-30">
                            <h3>About Us</h3>
                        </div>
                        <div class="about-prea">
                            <p class="about-pera1 mb-25">Moms are like…buttons? Moms are like glue. Moms are like pizza
                                crusts. Moms are the ones who make sure things happen—from birth to school lunch.</p>
                            <p class="about-pera1 mb-25">Moms are like…buttons? Moms are like glue. Moms are like pizza
                                crusts. Moms are the ones who make sure things happen—from birth to school lunch.</p>
                            <p class="about-pera1 mb-25">
                                My hero when I was a kid was my mom. Same for everyone I knew. Moms are untouchable.
                                They’re elegant, smart, beautiful, kind…everything we want to be. At 29 years old, my
                                favorite compliment is being told that I look like my mom. Seeing myself in her image,
                                like this daughter up top, makes me so proud of how far I’ve come, and so thankful for
                                where I come from.
                                the refractor telescope uses a convex lens to focus the light on the eyepiece.
                                The reflector telescope has a concave lens which means it bends in. It uses mirrors to
                                focus the image that you eventually see.
                                Collimation is a term for how well tuned the telescope is to give you a good clear image
                                of what you are looking at. You want your telescope to have good collimation so you are
                                not getting a false image of the celestial body.
                                Aperture is a fancy word for how big the lens of your telescope is. But it’s an
                                important word because the aperture of the lens is the key to how powerful your
                                telescope is. Magnification has nothing to do with it, its all in the aperture.
                                Focuser is the housing that keeps the eyepiece of the telescope, or what you will look
                                through, in place. The focuser has to be stable and in good repair for you to have an
                                image you can rely on.
                                Mount and Wedge. Both of these terms refer to the tripod your telescope sits on. The
                                mount is the actual tripod and the wedge is the device that lets you attach the
                                telescope to the mount.
                                Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones
                                who make sure things happen—from birth to school lunch.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <!-- Section Tittle -->
                    <div class="section-tittle mb-40">
                        <h3>Follow Us</h3>
                    </div>
                    <!-- Flow Socail -->
                    <div class="single-follow mb-45">
                        <div class="single-box">
                            <div class="follow-us d-flex align-items-center">
                                <div class="follow-social">
                                    <a href="#"><img src="{% static 'aznews/assets/img/news/icon-fb.png' %}" alt=""></a>
                                </div>
                                <div class="follow-count">
                                    <span>8,045</span>
                                    <p>Fans</p>
                                </div>
                            </div>
                            <div class="follow-us d-flex align-items-center">
                                <div class="follow-social">
                                    <a href="#"><img src="{% static 'aznews/assets/img/news/icon-tw.png' %}" alt=""></a>
                                </div>
                                <div class="follow-count">
                                    <span>8,045</span>
                                    <p>Fans</p>
                                </div>
                            </div>
                            <div class="follow-us d-flex align-items-center">
                                <div class="follow-social">
                                    <a href="#"><img src="{% static 'aznews/assets/img/news/icon-ins.png' %}"
                                            alt=""></a>
                                </div>
                                <div class="follow-count">
                                    <span>8,045</span>
                                    <p>Fans</p>
                                </div>
                            </div>
                            <div class="follow-us d-flex align-items-center">
                                <div class="follow-social">
                                    <a href="#"><img src="{% static 'aznews/assets/img/news/icon-yo.png' %}" alt=""></a>
                                </div>
                                <div class="follow-count">
                                    <span>8,045</span>
                                    <p>Fans</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- New Poster -->
                    <div class="news-poster d-none d-lg-block">
                        <img src="{% static 'aznews/assets/img/news/news_card.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About US End -->
</main>


{% endblock content %}

templates/aznews/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>News HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'aznews/assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'aznews/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/ticker-style.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'aznews/assets/css/style.css' %}">
</head>

<body>

    <!-- Preloader Start -->
    <!-- <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="assets/img/logo/logo.png" alt="">
                </div>
            </div>
        </div>
    </div> -->
    <!-- Preloader Start -->

    {% include "aznews/header.html" %}



    {% block content %}

    {% endblock content %}

    {% include "aznews/footer.html" %}



    <!-- JS here -->

    <!-- All JS Custom Plugins Link Here here -->
    <script src="{% static 'aznews/assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'aznews/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/popper.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'aznews/assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'aznews/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/slick.min.js' %}"></script>
    <!-- Date Picker -->
    <script src="{% static 'aznews/assets/js/gijgo.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'aznews/assets/js/wow.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/animated.headline.js' %}"></script>
    <script src="{% static 'aznews/assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Breaking New Pluging -->
    <script src="{% static 'aznews/assets/js/jquery.ticker.js' %}"></script>
    <script src="{% static 'aznews/assets/js/site.js' %}"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static 'aznews/assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/jquery.sticky.js' %}"></script>

    <!-- contact js -->
    <script src="{% static 'aznews/assets/js/contact.js' %}"></script>
    <script src="{% static 'aznews/assets/js/jquery.form.js' %}"></script>
    <script src="{% static 'aznews/assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'aznews/assets/js/mail-script.js' %}"></script>
    <script src="{% static 'aznews/assets/js/jquery.ajaxchimp.min.js' %}"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="{% static 'aznews/assets/js/plugins.js' %}"></script>
    <script src="{% static 'aznews/assets/js/main.js' %}"></script>
    <script>
        $("#newsletter_side_form").submit(function (e) {
            e.preventDefault()
            let serializedData = $(this).serialize()

            $.ajax({
                type: "POST",
                url: "{% url 'newsletter' %}",
                data: serializedData,
                success: function (response) {
                    $("#newsletter_side_form_message").append(
                        `
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            ${response.message}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        `
                    )
                },
                error: function (response) {
                    $("#newsletter_side_form_message").append(
                        `
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            ${response.responseJSON.message}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                        `
                    )
                }
            })
        })
    </script>
    <script>
        $(".pagination_number").click(function(e){
            e.preventDefault()
            let current_url=window.location.href.split('?')[0];
            let params= new URL(document.location).searchParams;
            let query=params.get("query");
            let href=$(this).attr('href');
            let new_url=`${current_url}${href}&query=${query}`;
            console.log(new_url)
            window.location.replace(new_url);
        })
    </script>

</body>

</html>

templates/aznews/contact.html
{% extends "aznews/base.html" %}

{% block content %}
<!-- ================ contact section start ================= -->
<section class="contact-section">
    <div class="container">


        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">Get in Touch</h2>
                {% if meassages %}


                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{message}}

                    {% if form.errors and form.non_field_errors %}

                    {{ form.non_field_errors}}

                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                {% endfor %}

                {% endif %}
            </div>
            <div class="col-lg-8">
                <form class="form-contact contact_form" action="" method="post" id="contactForm"
                    novalidate="novalidate">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"
                                    placeholder=" Enter Message"></textarea>
                                {{form.message.errors}}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control valid" name="name" id="name" type="text"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'"
                                    placeholder="Enter your name">
                                {{form.name.errors}}

                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control valid" name="email" id="email" type="email"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
                                    placeholder="Email">
                                {{form.email.errors}}

                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" name="subject" id="subject" type="text"
                                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'"
                                    placeholder="Enter Subject">
                                {{form.subject.errors}}

                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <button type="submit" class="button button-contactForm boxed-btn">Send</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 offset-lg-1">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-home"></i></span>
                    <div class="media-body">
                        <h3>Buttonwood, California.</h3>
                        <p>Rosemead, CA 91770</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                    <div class="media-body">
                        <h3>+1 253 565 2365</h3>
                        <p>Mon to Fri 9am to 6pm</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3>support@colorlib.com</h3>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ================ contact section end ================= -->


{% endblock content %}

templates/aznews/footer.html
<footer>
    <!-- Footer Start-->
    <div class="footer-area footer-padding fix">
         <div class="container">
             <div class="row d-flex justify-content-between">
                 <div class="col-xl-5 col-lg-5 col-md-7 col-sm-12">
                     <div class="single-footer-caption">
                         <div class="single-footer-caption">
                             <!-- logo -->
                             <div class="footer-logo">
                                 <a href="index.html"><img src="assets/img/logo/logo2_footer.png" alt=""></a>
                             </div>
                             <div class="footer-tittle">
                                 <div class="footer-pera">
                                     <p>Suscipit mauris pede for con sectetuer sodales adipisci for cursus fames lectus tempor da blandit gravida sodales  Suscipit mauris pede for con sectetuer sodales adipisci for cursus fames lectus tempor da blandit gravida sodales  Suscipit mauris pede for sectetuer.</p>
                                 </div>
                             </div>
                             <!-- social -->
                             <div class="footer-social">
                                 <a href="#"><i class="fab fa-twitter"></i></a>
                                 <a href="#"><i class="fab fa-instagram"></i></a>
                                 <a href="#"><i class="fab fa-pinterest-p"></i></a>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="col-xl-3 col-lg-3 col-md-4  col-sm-6">
                     <div class="single-footer-caption mt-60">
                         <div class="footer-tittle">
                             <h4>Newsletter</h4>
                             <p>Heaven fruitful doesn't over les idays appear creeping</p>
                             <!-- Form -->
                             <div class="footer-form" >
                                 <div id="mc_embed_signup">
                                     <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                     method="get" class="subscribe_form relative mail_part">
                                         <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                         class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                         onblur="this.placeholder = ' Email Address '">
                                         <div class="form-icon">
                                         <button type="submit" name="submit" id="newsletter-submit"
                                         class="email_icon newsletter-submit button-contactForm"><img src="assets/img/logo/form-iocn.png" alt=""></button>
                                         </div>
                                         <div class="mt-10 info"></div>
                                     </form>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
                 <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
                     <div class="single-footer-caption mb-50 mt-60">
                         <div class="footer-tittle">
                             <h4>Instagram Feed</h4>
                         </div>
                         <div class="instagram-gellay">
                             <ul class="insta-feed">
                                 <li><a href="#"><img src="assets/img/post/instra1.jpg" alt=""></a></li>
                                 <li><a href="#"><img src="assets/img/post/instra2.jpg" alt=""></a></li>
                                 <li><a href="#"><img src="assets/img/post/instra3.jpg" alt=""></a></li>
                                 <li><a href="#"><img src="assets/img/post/instra4.jpg" alt=""></a></li>
                                 <li><a href="#"><img src="assets/img/post/instra5.jpg" alt=""></a></li>
                                 <li><a href="#"><img src="assets/img/post/instra6.jpg" alt=""></a></li>
                             </ul>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
    <!-- footer-bottom aera -->
    <div class="footer-bottom-area">
        <div class="container">
            <div class="footer-border">
                 <div class="row d-flex align-items-center justify-content-between">
                     <div class="col-lg-6">
                         <div class="footer-copy-right">
                             <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                         </div>
                     </div>
                     <div class="col-lg-6">
                         <div class="footer-menu f-right">
                             <ul>                             
                                 <li><a href="#">Terms of use</a></li>
                                 <li><a href="#">Privacy Policy</a></li>
                                 <li><a href="#">Contact</a></li>
                             </ul>
                         </div>
                     </div>
                 </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>

templates/aznews/header.html
{% load static %}
<header>
    <!-- Header Start -->
    <div class="header-area">
        <div class="main-header ">
            <div class="header-top black-bg d-none d-md-block">
                <div class="container">
                    <div class="col-xl-12">
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="header-info-left">
                                <ul>
                                    <li><img src="{% static 'azews/assets/img/icon/header_icon1.png' %}" alt="">34ºc,
                                        Sunny </li>
                                    <li><img src="{% static 'azews/assets/img/icon/header_icon1.png' %}" alt="">Tuesday,
                                        18th June, 2019</li>
                                </ul>
                            </div>
                            <div class="header-info-right">
                                <ul class="header-social">
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'blog:post-create' %}"><i class="fas fa-plus"></i></a></li>
                                    <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
                                    <li>
                                        <a href="{% url 'blog:users' %}" title="Download Uers">
                                            <i class="fas fa-download"></i>
                                        </a>
                                    </li>
                                    {% else %}
                                    <li> <a href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i></a></li>

                                    {% endif %}
                                    
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-mid d-none d-md-block">
                <div class="container">
                    <div class="row d-flex align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-3 col-lg-3 col-md-3">
                            <div class="logo">
                                <a href="/"><img src="{% static 'azews/assets/img/logo/logo.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9 col-md-9">
                            <div class="header-banner f-right ">
                                <img src="{% static 'azews/assets/img/hero/header_card.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-bottom header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-10 col-lg-10 col-md-12 header-flex">
                            <!-- sticky -->
                            <div class="sticky-logo">
                                <a href="/"><img src="{% static 'azews/assets/img/logo/logo.png' %}" alt=""></a>
                            </div>
                            <!-- Main-menu -->
                            <div class="main-menu d-none d-md-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="/">Home</a>
                                        </li>
                                        {% for category in categories %}
                                        <li><a href="{% url 'post-by-category' category.pk %}">{{ category.name }}</a>
                                        </li>
                                        {% endfor %}
                                        <li><a href="{% url 'about' %}">About</a></li>
                                        <li><a href="{% url 'post-list' %}">Latest News</a></li>
                                        <li><a href="{% url 'contact' %}">Contact</a></li>
                                        <li><a href="#">Tags</a>
                                            <ul class="submenu">
                                                {% for tag in tags %}
                                                <li><a href="{% url 'post-by-tag' tag.pk %}">{{ tag.name}}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-4">
                            <div class="header-right-btn f-right d-none d-lg-block">
                                <i class="fas fa-search special-tag"></i>
                                <div class="search-box">
                                    <form action="#">
                                        <input type="text" placeholder="Search">

                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-md-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>